### PR TITLE
Fix lint warnings

### PR DESCRIPTION
**Pull request by halkyon**
I hope these are okay to do! I noted there was a `.golangci.yml` lint config in the repo, but there's some issues, so I tried to fix some of them. There's still a bunch of warnings remaining though which I haven't got to yet. I'm not sure if you run the linters often, or if there's a plan to add them to CI?

I separated the changes as much as possible so hopefully it's easier to review.

I also made an educated guess on which errors should continue to be ignored, looking at existing code that already does `_ = tbl.DecrRef()` and `_ = buf.Release()` in various places, but please let me know if something doesn't make sense here!

---
This change is [Reviewable](https://reviewable.io/reviews/outcaste-io/badger/2)

### CODE REVIEW

**Review by manishrjain — COMMENTED** [review]
> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/outcaste-io/badger/2)* status: all files reviewed, 3 unresolved discussions (waiting on @halkyon)

___
*[dir_unix.go, line 2 at r1](https://reviewable.io/reviews/outcaste-io/badger/2#-MyMve4e0hX_2ZjNhL39:-MyMve4e0hX_2ZjNhL3A:bucnler) ([raw file](https://github.com/outcaste-io/badger/blob/d2d7751cc55ac4147f8ea972428ae46c5b714e65/dir_unix.go#L2)):*
> ```Go
> //go:build !windows && !plan9
> // +build !windows,!plan9
> ```

Should this line be removed now?

`+build ...`
___
*[dir_windows.go, line 2 at r1](https://reviewable.io/reviews/outcaste-io/badger/2#-MyMviVQB0onBdPxRxsr:-MyMviVQB0onBdPxRxss:b-rkz2jj) ([raw file](https://github.com/outcaste-io/badger/blob/d2d7751cc55ac4147f8ea972428ae46c5b714e65/dir_windows.go#L2)):*
> ```Go
> //go:build windows
> // +build windows
> ```

same here.
___
*[y/file_dsync.go, line 2 at r1](https://reviewable.io/reviews/outcaste-io/badger/2#-MyMwDcl1TFMjCpZxuBA:-MyMwDcl1TFMjCpZxuBB:b-y7msob) ([raw file](https://github.com/outcaste-io/badger/blob/d2d7751cc55ac4147f8ea972428ae46c5b714e65/y/file_dsync.go#L2)):*
> ```Go
> //go:build !dragonfly && !freebsd && !windows && !plan9
> // +build !dragonfly,!freebsd,!windows,!plan9
> ```

and here. should this line be removed?

**Comment by manishrjain** [comment]
Thanks for the PR! Just a few comments. Rest looks good.

**Comment by halkyon** [comment]
> and here. should this line be removed?

Thanks for the feedback! It really depends on Go version compatibility, since the `go:build` tags were added in 1.17, but `+build` tags are still used in prior versions. In other projects, we left both `+build` and `go:build` for the most compatibility, so perhaps we could do the same here too?

**Comment by manishrjain** [comment]
Sounds good. Thanks for the PR!

**Pull request merged**
