### PR TITLE
chore(bloom): added Hash benchmark

### PR DESCRIPTION
**Pull request by SaveTheRbtz**
This adds an ability to replace hashing algorithms in the future and measure the impact.

For example, [xxh3 w/ AVX2](https://github.com/zeebo/xxh3) is capable of 20.1 ns/op (12.0 GB/s) on medium sized keys, meanwhile the current perf is:
```
name                time/op
Hash/hasher-1-8       2.40ns ± 3%
Hash/hasher-3-8       3.31ns ± 2%
Hash/hasher-4-8       3.55ns ± 5%
Hash/hasher-7-8       4.79ns ± 2%
Hash/hasher-8-8       4.80ns ± 1%
Hash/hasher-16-8      7.17ns ± 3%
Hash/hasher-32-8      11.9ns ± 2%
Hash/hasher-256-8      102ns ± 5%
Hash/hasher-1024-8     427ns ± 3%
Hash/hasher-4096-8    1.68µs ± 1%

name                speed
Hash/hasher-1-8      417MB/s ± 3%
Hash/hasher-3-8      907MB/s ± 2%
Hash/hasher-4-8     1.13GB/s ± 5%
Hash/hasher-7-8     1.46GB/s ± 2%
Hash/hasher-8-8     1.67GB/s ± 1%
Hash/hasher-16-8    2.23GB/s ± 3%
Hash/hasher-32-8    2.70GB/s ± 2%
Hash/hasher-256-8   2.52GB/s ± 5%
Hash/hasher-1024-8  2.40GB/s ± 4%
Hash/hasher-4096-8  2.44GB/s ± 1%
```

This is a slightly improved version of dgraph-io/badger#1774

---
This change is [Reviewable](https://reviewable.io/reviews/outcaste-io/badger/5)

### CODE REVIEW

**Review by manishrjain — APPROVED** [review]
:lgtm: Got a small comment.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/outcaste-io/badger/5#-:-MzLRigd5p0z5CuGcsYs:b7i7bsa)* status: all files reviewed, 1 unresolved discussion (waiting on @SaveTheRbtz)

___
*[y/bloom_test.go, line 145 at r1](https://reviewable.io/reviews/outcaste-io/badger/5#-MzLRbwnDpKQL7jl_0Nl:-MzLRbwnDpKQL7jl_0Nm:b4svrkt) ([raw file](https://github.com/outcaste-io/badger/blob/f105212393ace8f6c74b1630d2cba540be088179/y/bloom_test.go#L145)):*
> ```Go
> 				acc = Hash(d)
> 			}
> 			runtime.KeepAlive(acc)
> ```

Doubt you need runtime keepalive for this. `acc` is a basic data type.

**Comment by manishrjain** [comment]
Also have a look at the merge conflict.

**Comment by SaveTheRbtz** [comment]
*[y/bloom_test.go, line 145 at r1](https://reviewable.io/reviews/outcaste-io/badger/5#-MzLRbwnDpKQL7jl_0Nl:-MzNz7AGEwbNDHtMUu0H:b-896fix) ([raw file](https://github.com/outcaste-io/badger/blob/f105212393ace8f6c74b1630d2cba540be088179/y/bloom_test.go#L145)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary><blockquote>

Doubt you need runtime keepalive for this. `acc` is a basic data type.
</blockquote></details>

Done.

**Review by poonai — APPROVED** [review]

**Comment by SaveTheRbtz** [comment]
done.

**Pull request merged**
