### PR TITLE
Bump xxhash v2

### PR DESCRIPTION
**Pull request by eh-steve**
This change is [Reviewable](https://reviewable.io/reviews/outcaste-io/badger/7)

### CODE REVIEW

**Comment by manishrjain** [comment]
@eh-steve -- can you please sign the CLA?

**Review by manishrjain — APPROVED** [review]
:lgtm: Will merge after you sign the CLA.

> *[Reviewable](https://reviewable.io/reviews/outcaste-io/badger/7#-:-Mzr9Fez55oT7UxM2JtR:bbrqxo)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @jarifibrahim)

**Review by jarifibrahim — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/outcaste-io/badger/7#-:-MztOc128nZPZJfJZb4O:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved

**Comment by jarifibrahim** [comment]
Thank you for your contribution @eh-steve 🎉  . Merged the PR 🚀 .

**Pull request merged**
